stages:
  - validate
  - build
  # - dev-deploy
  # - prod-deploy

before_script:
    - yum install docker -y
    - systemctl start docker 
    - systemctl enable docker

variables-view: 
  stage: validate
  script: 
    - echo $TEST 
    - docker images
    - helm list
    - kubectl get po 
  tags: 
    - docker 


admin-view-docker-build:
  stage: build
  script:
    - cd admin-vew 
    - echo $TEST
    - aws ecr login
    - docker build -t ecr-url/reponame:tag 
    - docker push ecr-url/reponame:tag 
  tags: 
    - docker